### PR TITLE
Raised solrconfig version as followup of ticket #204

### PR DESCRIPTION
**Pull request by timoschmidt**
Followup of ticket #204

### CODE REVIEW

**Comment by irnnr** [comment]
Since this is master/3.2.0 also increase the version in the name

**Comment by irnnr** [comment]
Go ahead and merge after tweaking the version

**Comment by timoschmidt** [comment]
@irnnr 
I've changed the version to 4.0.0 since this was the next version in the last discussion. What about other schema changes? Do we change the version, when we release a new EXT:solr version of only when a schema change is really done?

**Comment by irnnr** [comment]
Until now I only changed the name attribute whenever something actually changed. Looks good to me.

**Pull request merged**
