### PR TITLE
[BUGFIX] User groups always compared as integers

### PR DESCRIPTION
**Pull request by balasch**
# What this pr does

Replaces explode with GeneralUtility::intExplode

Fixes: #3249

### CODE REVIEW

**Comment by dkd-kaehm** [comment]
@balasch 
Thanks for the fix.

Could you please port the change into release-11.5.x branch?

**Review by dkd-kaehm — APPROVED** [review]
LGTM

**Comment by balasch** [comment]
Also a new PR for 11.5.x: https://github.com/TYPO3-Solr/ext-solr/pull/3253

**Comment by dkd-kaehm** [comment]
Ports: 
* main 22c2d7baf902fd3eabddab43ef3d7e521f87ca6a
* release-11.5.x eab5887f1a3c27b784655d738c352d445183d976

**Pull request merged**
