### PR TITLE
[TASK] Use bootstrap modals for danger zone items and remove usage of ActionButtonViewHelper

### PR DESCRIPTION
**Pull request by timoschmidt**
Uses bootrap modals from TYPO3 core for danger zone buttons and remove the ActionButtonViewHelper since this is possible with native fluid view helpers.

Fixes: #127

### CODE REVIEW

**Comment by irnnr** [comment]
Hmm, this is not the same unfortunately. AFAIK the link view helper renders an anchor tag, but EXT:solr's action button renders a form with a button that submits the form. This was on purpose as the form submits via POST, the link is a GET. These are destructive actions and should not use GET as that allows to reload, while a POST causes the browser to prompt when reloading. In theory it should even be a DELETE request although granted the whole thing is not fully REST compliant anyway.

**Comment by timoschmidt** [comment]
I see the point, but in the TYPO3 backend nearly all of these "destructive actions" are implemented with links and on the other hand the server side implementation should avoid this by doing a redirect instead of relying on the browsers behaviour. Nevertheless it can be implemented by using the form viewhelper of fluid. I'll check that and check how modals can be used with these forms.

**Comment by timoschmidt** [comment]
I've changed the implementation to use forms with a post request and implemented an own modal handler to use this in all backend dialogues.

**Comment by irnnr** [comment]
cool, thanks!

**Pull request merged**
