### PR TITLE
[BUGFIX] Assign undefined variable $pageId

### PR DESCRIPTION
**Pull request by andreasfernandez**
Assign the pid of the currently processed record to the undefined ``$pageId`` variable.

### CODE REVIEW

**Comment by timoschmidt** [comment]
Thx for your pull request. I'll check it now!

**Comment by timoschmidt** [comment]
I think we need to refine the patch because after applying the patch i could not index a page and get a queue error for each.

**Comment by timoschmidt** [comment]
Thanks for your contribution. Checked it with my system and everything looks good now.

**Comment by irnnr** [comment]
This was a long known issue and left open exactly because of the side effect. But thanks for fixing it/finding a fix for the side effect! 
We'll have to keep an eye on it nevertheless as this involves how the hash is built that verifies the indexer request is legit, preventing DOS attacks through indexer requests as these are uncached.

**Pull request merged**
