### PR TITLE
WIP|FEATURE: Allow different configurations for pages table

### PR DESCRIPTION
**Pull request by DanielSiepmann**
- To keep indexing queue configuration for custom pages types.

Related: #639

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
This is not the full Pull Request, just one part of the fix.

This should fix the first issue not being able to index custom page types at all.

**Comment by DanielSiepmann** [comment]
Would be nice if someone can check whether my tests are helpful and cover the necessary parts.
Hopefully I covered everything that's necessary for this fix.

**Comment by yhermes** [comment]
Currently if you change content on an already indexed page and queue again, only the not changed pages get queued again.

**Comment by timohund** [comment]
@DanielSiepmann Thx for your work on this. I'll try to have a look on this in the next days.

**Comment by timohund** [comment]
@DanielSiepmann will have a look on this in the next days and we can proceed on this later.

**Comment by DanielSiepmann** [comment]
We still need to tackle the issue that the page is still queued as `page` for mountpoints:
image
Also the added tests are not good enough, as they didn't show the issue with allowed doktype.

**Comment by timohund** [comment]
Since there is a PR for #715 can you maybe check after merging if the problem still exists?

**Comment by timohund** [comment]
I've rebased the patch and fixed some minor issues

I'll close this PR

@DanielSiepmann 
@yhermes 

Can you verfiy if everthing is working fine when you use (Keep in mind, you need to update the Apache Solr Server):

#778

**Pull request closed without merging**
