### PR TITLE
[TASK] Dispatch signals in search controller actions

### PR DESCRIPTION
**Pull request by Mabahe**
Resolves: #1889

### CODE REVIEW

**Comment by timohund** [comment]
@Mabahe Thanks for the patch. Can you please add a description to the issue and maybe add some words to the documentation, how these signals can be used?

**Comment by Mabahe** [comment]
Jep, sure

**Comment by timohund** [comment]
@Mabahe  do you have the time to add some documentation, that we can merge this pr?

**Comment by Mabahe** [comment]
Added a chapter to the documentation

**Comment by timohund** [comment]
@Mabahe thanks for the patch and the documentation, i'll test and merge it.

**Pull request merged**
