### PR TITLE
[TASK] Allow to install on TYPO3 v10 #2447

### PR DESCRIPTION
**Pull request by markuskobligk**
# What this pr does

Allow to install EXT:solr via composer on v10

# How to test

Install EXT:solr via composer

Fixes: #2447

### CODE REVIEW

**Comment by markuskobligk** [comment]
To make EXT:solr work on v10 I had to use the version with https://github.com/TYPO3-Solr/ext-solr/pull/2455 together with this PR, otherwise the Solr backend modules failed with a missing extension name error.

**Comment by timohund** [comment]
@markuskobligk Thanks for preparing. I think we should wait with merging that, since to support TYPO3 10 some more stuff is missing, especially the migration of the TSFE initialization.

**Comment by markuskobligk** [comment]
@timohund Yes, makes sense

**Comment by timohund** [comment]
@markuskobligk resolved with https://github.com/TYPO3-Solr/ext-solr/pull/2529

**Pull request closed without merging**
