### PR TITLE
[BUGFIX] Avoid fatal when indexing configuration is empty

### PR DESCRIPTION
**Pull request by Mabahe**
Throw an exception instead to trigger a failed indexing.

 Resolves: #371

### CODE REVIEW

**Comment by timoschmidt** [comment]
I think this is a leftover from the configuration object changes and could be done easier.
I've allready replaced this part in a branch where the deprecated parts should get removed.

https://github.com/timoschmidt/ext-solr/commit/dec6f9467de042ec3a3d4b6b71211391286a8c0a

**Comment by timoschmidt** [comment]
Fixed with #377 please reopen when still needed

**Comment by Mabahe** [comment]
Fix in #377 looks fine, THX. But this is sadly no leftover. This problem exists since 2.0 :-)

Will reopen it for PR for 3.1 and 4.0.

**Comment by timoschmidt** [comment]
No i mean, using the method instead the array keys is a leftover. I've ported your change in my commit to master. We can backport it to 3.1 and 4.0 as well, or does anything else not work with the change in master for you?

**Pull request closed without merging**
