### PR TITLE
[BUGFIX] Index Queue is not updated when changing page properties of …

### PR DESCRIPTION
**Pull request by markuskobligk**
…rootpage

### CODE REVIEW

**Comment by peterkraume** [comment]
Thanks a lot for the patch! I've tested it and it worked fine for me! Can you please create another PR for the release-3.0.x branch?

**Comment by markuskobligk** [comment]
PR for 3.0.x release:
https://github.com/TYPO3-Solr/ext-solr/pull/61

**Comment by irnnr** [comment]
Can you explain what the issue was?

**Comment by markuskobligk** [comment]
When changing any page property of a page that is marked as "siteroot" the field "changed" in table tx_solr_indexqueue_item does not get updated. Changes to those siteroot pages don't get indexed unless the whole index queue for pages gets initialized again.

See also: https://forge.typo3.org/issues/66180

**Comment by irnnr** [comment]
Please always wrap your conditional branches in curly braces.

**Pull request merged**
