### PR TITLE
[TASK] Added GPL-2 license file

### PR DESCRIPTION
**Pull request by thomashohn**
Should solve #845 - took the one from TYPO3 - OK?

### CODE REVIEW

**Comment by timohund** [comment]
@dkd-dobberkau What do you think about this?

**Comment by dkd-dobberkau** [comment]
+1 for adding the GPL but as this here: https://choosealicense.com/licenses/gpl-3.0/
Additionally, we need to see if we follow the recommended boilerplate text for each file in the project. 

See: Note: The Free Software Foundation recommends taking the additional step of adding a boilerplate notice to the top of each file. The boilerplate can be found at the end of the license.

**Comment by thomashohn** [comment]
I would say nearly that boiler plate code..

**Comment by timohund** [comment]
@dkd-dobberkau 

This is the current header:

```php
/***************************************************************
 *  Copyright notice
 *
 *  (c) $year $author <$email>
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/
```

Should we use this and check if it is used in all files?

**Comment by irnnr** [comment]
I'd argue let's add the license file for what we have right now - GPL2+. In another issue we can then upgrade the license to GPL3 and the file headers.

**Comment by irnnr** [comment]
Updating/upgrading the license is a different issue to me than what this particular ticket was about - adding the license file at all.

**Comment by timohund** [comment]
@irnnr I would agree and if needed do this in a seperat ticket. 

@dkd-dobberkau Should we merge this?

**Comment by dkd-dobberkau** [comment]
fine with me. someone else must do the commit.

**Comment by irnnr** [comment]
@thomashohn can you revert this PR to the GPLv2+ license file? - just revert the GPLv3 commit.

**Comment by irnnr** [comment]
I opened a separate issue to upgrade the license to GPLv3: #935

**Comment by thomashohn** [comment]
@timohund I reverted to the GPL v2 and you can merge it now

**Pull request merged**
