### PR TITLE
Added configuration "plugin.tx_solr.results.resultsHighlighting.useFastVectorHighlighter" to use a faster highlighter when needed.

### PR DESCRIPTION
**Pull request by timoschmidt**
Can be used to enable "hl.useFastVectorHighlighter" to improve the highlighting performance.

Fixes: #193

### CODE REVIEW

**Comment by dkd-friedrich** [comment]
I could successfully activate and test the FastVectorHighlighter, but I encountered an error with low fragment size setting

```
java.lang.IllegalArgumentException: fragCharSize(0) is too small. It must be 18 or higher.
	at org.apache.lucene.search.vectorhighlight.BaseFragListBuilder.createFieldFragList(BaseFragListBuilder.java:51)
	at org.apache.lucene.search.vectorhighlight.SimpleFragListBuilder.createFieldFragList(SimpleFragListBuilder.java:39)
	at org.apache.lucene.search.vectorhighlight.FastVectorHighlighter.getFieldFragList(FastVectorHighlighter.java:232)
	at org.apache.lucene.search.vectorhighlight.FastVectorHighlighter.getBestFragments(FastVectorHighlighter.java:185
```

Though I couldn't find a notice about this requirement in the wiki, I think we could add a notice in the TypoScript configuration

**Comment by timoschmidt** [comment]
I've added a documentation in the TypoScript that useFastVectorHighlighter is only usable with a fragementSize larger then 18 and throw an Exception now, when this is not the case.

Does everything beside that look good?

**Comment by dkd-friedrich** [comment]
> Does everything beside that look good?

Yes, with fragment size >= 18 highlighting worked as expected

**Comment by irnnr** [comment]
Please don't make this configurable, simply replace the existing highlighter.

**Comment by timoschmidt** [comment]
Hmm, but it would not work with all fields in the schema because it requires termVectors=on, termPositions=on and termOffsets=on so highlighting would be impossible for the other fields. Or do you think it is only required for content?

**Pull request merged**
