### PR TITLE
[BUGFIX] Ensure record exists before asserting if draft

### PR DESCRIPTION
**Pull request by dogawaf**
# What this pr does

This fix an error in case a record was not found in the garbage collector process.

Fixes: #3531

### CODE REVIEW

**Comment by dogawaf** [comment]
The fix is maybe not the good one, as it can hide the real issue: why the record was not found?

**Comment by dkd-kaehm** [comment]
> The fix is maybe not the good one, as it can hide the real issue: why the record was not found?

Did you find out why it was so on your system?

**Comment by koehnlein** [comment]
I just added some information how to reproduce it in #3531:

It happens if a record is deleted. `BackendUtility::getRecord()` is executed with the uid of the deleted record and returns `null`

**Comment by dkd-friedrich** [comment]
I'm also not exactly sure why an already deleted record gets processed by the RecordMonitor or the GarbageCollector, but as draft records will be ignored anyway it should be safe to fix this issue that way.

**Review by dkd-friedrich — APPROVED** [review]
LGTM

**Comment by dkd-friedrich** [comment]
@dogawaf Thanks for providing a pr, I'll do a backport to 11.5.

**Pull request merged**
