### PR TITLE
[BUGFIX] Fix sorting and counts in statistics module

### PR DESCRIPTION
**Pull request by dkd-kaehm**
* fix "top 5" and "search statistics" queries for correct calculations
* remove PHP calculations where possible and replace it with SQL

fixes: #1579, closes: #1573, fixes: #1572

### CODE REVIEW

**Comment by dkd-kaehm** [comment]
@mschwemer could you please check if this works as expected.

**Comment by mschwemer** [comment]
@dkd-kaehm Thanks. The counted numbers seem ok and deliver the same results for the TOP5 and the TOP100.

But the percentage is way too low. 
solr_search_percentage

Until recently the top100 summed up to 100%. Our top searches had values from 3 to 8 percent.

**Comment by mschwemer** [comment]
Here is a screen  with numbers from master
solr_search_percentage_old

**Comment by dkd-kaehm** [comment]
@mschwemer please check again, I fixed it. We must count the rows by root page id.
I guess you are using multiple site roots...

**Comment by dkd-kaehm** [comment]
DBAL converts decimals to string for keeping high precision: ["For compatibility reasons this type is not converted to a double as PHP can only preserve the precision to a certain degree. Otherwise it approximates precision which can lead to false assumptions in applications."](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#decimal)

So the test could fail on other DB platforms.

**Comment by dkd-kaehm** [comment]
@mschwemer: could you please review this PR. 
Does it work as expected?

**Comment by mschwemer** [comment]
@dkd-kaehm Thx for the reminder ... yes it works as expected.

**Comment by dkd-kaehm** [comment]
Thanks Marcus, I'll do the same for 7.0

**Pull request merged**
