### PR TITLE
[TASK] Migrate CommandController to Symfony command

### PR DESCRIPTION
**Pull request by georgringer**
Instead of using an extbase command controller, use a symfony command
for updating the connections.
## ./typo3/sysext/core/bin/typo3 solr:updateConnections

Fixes: #707

### CODE REVIEW

**Comment by timohund** [comment]
Looks good, thx for the pull request. I think we should talk about the 7.6 compatibility. I did an have an appointment with georg on wednesday. Please do not merge it before.

**Comment by timohund** [comment]
We can merge this after dropping the 7 LTS Support.

**Comment by kasperligaard** [comment]
This issue should have it's milestone set to 7.0, right?

**Comment by timohund** [comment]
@kasperligaard i've changed it to 7.0 thanks

**Comment by dkd-kaehm** [comment]
Sorry, no needs for currently supported EXT:Solr versions.
Closing it.

**Pull request closed without merging**
