### PR TITLE
[BUGFIX] Fix getAllRequirementsMet returns true too soon

### PR DESCRIPTION
**Pull request by netcoop**
RequirementsService->getAllRequirementsMet() returns true as soon as one requirement is met (#2374)

# What this pr does

With this PR true is only returned when ALL given requirements are fullfilled, not just one

Fixes: #2374

### CODE REVIEW

**Comment by timohund** [comment]
@netcoop Can you add a unit test, that fails without the fix and passes with the fix?

**Comment by netcoop** [comment]
I was looking into that already but didn't get the unit testing working... need some up-to-date howto

**Comment by timohund** [comment]
@netcoop The contribution guide lines describe how to run them: https://github.com/TYPO3-Solr/ext-solr/blob/master/CONTRIBUTING.md#automated-tests

**Comment by netcoop** [comment]
Thanks, will give that a try soon!

**Pull request closed without merging**
