### PR TITLE
[BUGFIX] hierarchical fields need to add trailing slash

### PR DESCRIPTION
**Pull request by AndreasA**
In order to be able to differentiate between 0-foo and 0-foobar
when using facet.prefix it is necessary to use a trailing slash
that way when using facet.prefix 0-foo/ only the 0-foo/ will
be found and not also 0-foobar/

Resolves: #683

### CODE REVIEW

**Comment by timohund** [comment]
@AndreasA Thanks for the patch, i'll check it, beside that we need to keep in mind that this also requires a change in EXT:solrfluid. I'll take care of that.

**Comment by timohund** [comment]
@AndreasA there is one failing integration test. I guess the assertion needs to be updated to index.php?id=1&amp;q=prices&amp;tx_solr%5Bfilter%5D%5B0%5D=pageHierarchy%253A%252F1%252F&amp; can you check it?

**Comment by AndreasA** [comment]
I found an issue before I checked the test.
I fixed that issue, it was related to the URL and Hierarchical menus.

This should be fixed with the additional commit.
If this doesn't fix the hierarchy issue, I will check the results in regards to further changes.

**Comment by AndreasA** [comment]
OK. Three tests still seem to be failing. Will take care of those tomorrow.

**Comment by AndreasA** [comment]
One question: should we also change the variantId to have a trailing slash?
Though I think it is unnecessary as the variantId is only used with equals and who knows how often we would have to change that :)

**Comment by timohund** [comment]
@AndreasA Thanks for your work on that. Regarding the variantId. Do you see a need for that? An option could be we the variantId is used to reflect a hierarchical structure, are you using it like this? I yes i would propose to open a seperate issue.

**Comment by AndreasA** [comment]
No, I am not using it that way currently.
And if one intends to use it hierarchical one could always create a separate field, so I don't really see a need for that but maybe someone else does?

**Comment by timohund** [comment]
I'll merge this pr and take care on the solrfluid adaption, if somebody sees a need on changing the variantId please open a new issue.

**Pull request merged**
