### PR TITLE
[TASK] Remove a hint about optimize index scheduler task from docs.

### LINKED ISSUE #1125: [Task] check whether a hint for "optimize index scheduler task" in the docs is still valid
Is 
https://github.com/TYPO3-Solr/ext-solr/blob/f8ed95931655026224b95049726e450a9603ecbb/Documentation/Solr/IndexMaintenance.rst#initializing-the-spell-checker still OK or can we drop it from docs?

Question coming from Slack https://typo3.slack.com/archives/ext-solr/p1488534076685771

### PR DESCRIPTION
**Pull request by dkd-kaehm**
We do not recommend anymore to optimize cores manually.

This closes #1125

### CODE REVIEW

**Comment by timohund** [comment]
This is something different. The part you want to remove explain how to create cores manually with the solr api. I guess ingo was talking about https://github.com/TYPO3-Solr/ext-solr/blob/f8ed95931655026224b95049726e450a9603ecbb/Documentation/Solr/IndexMaintenance.rst#initializing-the-spell-checker and the part with the "Optimize Index Task for the scheduler."

I think we can remove this and need to check if the curl command 

```
curl 'http://host:port/path-to-solr/select/?spellcheck=true&spellcheck.build=true'
```

is still required. Of if this is done by solr automatically meanwhile, then we can remove this too.

**Comment by dkd-kaehm** [comment]
Oooh, yes. wrong block deleted. but currently fixed.

**Comment by irnnr** [comment]
correct, https://github.com/TYPO3-Solr/ext-solr/blob/f8ed95931655026224b95049726e450a9603ecbb/Documentation/Solr/IndexMaintenance.rst#optimizing-the-index

**Comment by irnnr** [comment]
Also, documents are now indexed in near-real-time, so committing them is not needed anymore 
https://github.com/TYPO3-Solr/ext-solr/blob/f8ed95931655026224b95049726e450a9603ecbb/Documentation/Solr/IndexMaintenance.rst#committing-pending-documents

**Comment by timohund** [comment]
@irnnr Thanks for the hint, should we open a new issue for this?

**Comment by AndreasA** [comment]
This definitely removed the wrong section.
Btw. is there a reason why executing solr optimizing isn't recommended anymore?

**Pull request merged**
