### PR TITLE
[!!!][TASK] Remove deprecated Node class

### PR DESCRIPTION
**Pull request by dkd-friedrich**
# What this pr does

Removes deprecated class ApacheSolrForTypo3\Solr\System\Solr\Node and it's usages.

- Replace deprecated Node class with Endpoint
- Replace getUsername/getPassword with getAuthentication()
- Change SolrConnection->getNode() to SolrConnection->getEndpoint
- Update documentation and release notes

Resolves: #3630

### CODE REVIEW

**Comment by dkd-friedrich** [comment]
Originates from #3665

**Comment by dkd-friedrich** [comment]
Necessary adjustments made, final tests are still pending

We have to decide if we still want to support the `solr/` path segment in the configuration.

**Comment by dkd-friedrich** [comment]
> We have to decide if we still want to support the `solr/` path segment in the configuration.

We discussed this and we'll drop this backwards compatibility with EXT:solr 12, to reduce the complexity and to follow the standards.

**Review by dkd-kaehm — APPROVED** [review]
LGTM,
can merge.

**Pull request merged**
