### PR TITLE
[BUG] Fix Initialize Solr Connection again

### PR DESCRIPTION
**Pull request by thomashohn**
Fixes: #1215

### CODE REVIEW

**Comment by timohund** [comment]
@thomashohn Can you please add a todo to remove the 7.6 stuff in EXT:solr 7.0.0

**Comment by thomashohn** [comment]
Added todo

**Comment by dkd-kaehm** [comment]
on CMS@dev-master Translation does not do the thing:

bildschirmfoto 2017-03-30 um 17 34 28

using:
`\TYPO3\CMS\Extbase\Utility\LocalizationUtility::translate('cache_initialize_solr_connections', 'solr')`
solves that and works in 7.6 to ;) .

of course all caches flushed incl. opcache and reloaded the backend.

**Comment by thomashohn** [comment]
Weird - works fine at my end.
My suggestion would be to leave the code as it is - since

- 7.6 LTS support will soon be dropped.

- It has "always" been hardcoded.

- It's the second time I have to "fix" this with TYPO 8 - so I would rather be conform with the core and only pass the language reference.

This shows my installation - the translation of the label seems to work without any problems
screen shot 2017-03-31 at 06 07 50

**Comment by timohund** [comment]
I've tested thomas patch and it works on both systems. @dkd-kaehm could it be that your TYPO3 dev-master was not uptodate? I would propose to merge it and remove the 7.6 compatibility right after the release.

**Comment by timohund** [comment]
Added note to #950 for the removal in the next release. Thx @thomashohn & @dkd-kaehm

**Pull request merged**
