### PR TITLE
[TASK] Use ::class and short array syntax in ConnectionManager

### PR DESCRIPTION
**Pull request by timohund**
* This PR adds Tests for the ConnectionManager
* Uses the ::class and short array syntax in the ConnectionManager
* Reduces duplicate code

### CODE REVIEW

**Comment by schleger** [comment]
84.243.205.150. My ip adress.no connected

**Comment by timohund** [comment]
@schleger what do you want to say with your comment?

**Comment by schleger** [comment]
My ip adress84.243.205.150.My run end no connect.

**Comment by timohund** [comment]
Which run?

**Comment by irnnr** [comment]
😂 I think this is spam

**Pull request merged**
