### PR TITLE
Use PHP generator to prevent processing of all available site

### PR DESCRIPTION
**Pull request by sfroemkenjw**
# What this pr does

Use PHP generator with yield to process just the available sites needed

# How to test

With over 300 root pages it needs over 30 seconds to build up all available sites. With help of a PHP generator we can stop processing all available sites if just the first site is requested. It's also helpful to just check, if there are available sites.

This should speed up performance a lot.

### CODE REVIEW

**Comment by sfroemkenjw** [comment]
Wohouuuu. 316ms to render the index queue module. Happy review ;-)

**Comment by cricog** [comment]
Hi! Do you plan to backport this correction on the 12 branch ?

**Comment by sfroemkenjw** [comment]
Hi @cricog,

@dkd-kaehm already asked me to provide a patch for TYPO3 12. Maybe I will find time this week.

Have a good start into this week

Stefan

**Comment by sfroemkenjw** [comment]
Hi @cricog I have added a patch for TYPO3 12.4:
https://github.com/TYPO3-Solr/ext-solr/pull/4154
Tests green. Yeah.

**Pull request closed without merging**
