### PR TITLE
✨ DDEV Configuration

### PR DESCRIPTION
**Pull request by WebsiteDeveloper**
This PR adds DDEV config to ease local development

See: https://ddev.readthedocs.io

### CODE REVIEW

**Comment by timohund** [comment]
@WebsiteDeveloper Thanks for your PR, we allready have a ddev environment in a seperate repository: https://github.com/TYPO3-Solr/solr-ddev-site do you know that?

I would propose to have that in a seperate repository because:

* With that you have a complete running site with the introduction package.
* We can create new versions with different PHP/TYPO3 versions whatever

**Comment by WebsiteDeveloper** [comment]
I didn't know that 
I still think that it provides some value for developing the extension itself. Which is the main usecase this intends to solve.

**Comment by timohund** [comment]
@WebsiteDeveloper Ah ok, can you the please provide a snipped for the documentation how that can be used?

**Comment by WebsiteDeveloper** [comment]
sure will do :)

**Comment by dkd-kaehm** [comment]
Would propose to add the hint about https://github.com/TYPO3-Solr/solr-ddev-site existence and its usage instead of billow out this Repo. ddev is not а hub of the universe.

**Pull request closed without merging**
