### PR TITLE
[TASK] Fix scrutinizer issues in Queue

### LINKED ISSUE #1012: [TASK] Fix scrutinizer issues in Queue

### PR DESCRIPTION
**Pull request by thomashohn**
Should fix #1012. @timohund please have a look at the deprecations

### CODE REVIEW

**Comment by timohund** [comment]
I'll have a look at that one later

**Comment by irnnr** [comment]
I'd say if you're not sure whether a method is used, just deprecate it, but do not remove it yet. Someone else might use it.

**Comment by thomashohn** [comment]
I suggest we deprecate both methods with 6.1 then

**Comment by timohund** [comment]
@thomashohn can you remove the todo and do in both a GeneralUtility::logDeprecatedFunction(); i think then we can remove them in 7.0

**Pull request merged**
