### PR TITLE
[FEATURE] Facet ViewHelper should respect facet requirements

### PR DESCRIPTION
**Pull request by geldmacher**
No big deal, but missing.

### CODE REVIEW

**Comment by irnnr** [comment]
If you check the Travis build log you can see that you need to fix some code style issues. 
Ideally if you could provide a test for this issue that'd be very helpful, too. Simply check the other facet/template related tests. Just create a little bit of data and configuration and render a small template with the facet view helper in it. Then check both the positive case and an error case.

**Comment by geldmacher** [comment]
I have fixed the indentation issue. The travis build log has stil two issues i cannot fix, i think.
At the moment i have no time for more, sry. Perhaps this is enough for step 1!?

**Comment by irnnr** [comment]
ok thanks. We might have to wait until Timo is back from vacation. Meanwhile, why not try to put together a test for your issue :)

**Comment by irnnr** [comment]
Hey @geldmacher still working on the tests?

**Comment by geldmacher** [comment]
Not even started. Do not wait for me ... Sry

**Comment by irnnr** [comment]
ok, thanks for the update

**Comment by timohund** [comment]
Closing because no feedback was given. Please open a new PR

**Pull request closed without merging**
