### PR TITLE
[BUGFIX] Use rawurldecode on facets to handle `+`

### PR DESCRIPTION
**Pull request by alappe**
The test case might be a bit weak and this PR does not regard any *en*coding of those values, since we're not using them in our projects, so I can't attest to it. However, this fixes my issues, so I'm looking for feedback…

Related: #1656

### CODE REVIEW

**Comment by timohund** [comment]
@alappe Thanks for the pr. Are you using the old templating only or in combination with solrfluid?

**Comment by alappe** [comment]
Together with solrfluid but mostly with js code doing ajax calls.

**Comment by hirnschmalz** [comment]
Is there a reason why this PR hasn't made it into to code after almos 2 years?

**Comment by timohund** [comment]
@hirnschmalz yes because it has not be rebased. The diff show's changes in **203** files. If you have the time it would be nice if you could rebase it and create a PR were the changes can be seen directly.

**Comment by 3l73** [comment]
Closed in favor for #2806 

New pull request based on current master with changes from this pull request.

**Pull request closed without merging**
