### PR TITLE
IndexMaintenance documentation: fix params in create core call

### PR DESCRIPTION
**Pull request by andristeiner**
With the current command, i'll end up with a datadir of `/<installation-path>/server/solr/core_de/dataDir=../../data/german/`

### CODE REVIEW

**Comment by schoeppe** [comment]
I am missing this change in the current releases - the documentation shows still the duplicate dataDir in the command.

**Comment by dkd-kaehm** [comment]
current release is 8.0 you mean 7.5
Isn't backported. 13ea6feeff4e3e7707ad9291d0286bd64edb7541 must be cherry-picked into 7.5
@schoeppe could you do that?

**Comment by timohund** [comment]
It is only merged into master and not into the 8.0.x release branch. Therefore it will be part of 8.1.0, otherwise you could backport it to the 8.0.x branch and it will be part of the next 8.0.x release.

**Comment by schoeppe** [comment]
I created pull requests for the release branches 7.5.x, 7.0.x and 6.5.x.
Release branch for 8.0.x was already up to date.

**Pull request merged**
