### PR TITLE
WIP [BUGFIX] MM relation value resolution

### PR DESCRIPTION
**Pull request by cjanody**
getRelatedItemsFromMMTable returns only the first matching item when using enableRecursiveValueResolution. This is due to the use of a return in the foreach loop instead of merging the result of getRelatedItems.

Sample:
ModelA has n:m relations to modelB and ModelB n:m relations to ModelC

```
plugin.tx_solr {
  index.queue {
    A = 1
    A {
      table = tx_sample_domain_model_modela
      fields {
        title = title
        modelC_stringM = SOLR_RELATION
        modelC_stringM {
          localField = modelb
          multiValue = 1
          foreignLabelField = modelc.title
          enableRecursiveValueResolution = 1
          removeDuplicateValues = 1
        }
      }
    }
  }
}
```

Whitout the patch, only the first title of linked ModelC is returned

Thanks for reading.

### CODE REVIEW

**Comment by timohund** [comment]
I would really propose to add a functional test that fails without the patch and passes with the patch.

**Comment by timohund** [comment]
@cjanody your last commit add's a fixture, but not a testcase. Will you add a testcase in addtion?

**Comment by cjanody** [comment]
@timohund I will add the testcase as soon as possible. Thks

**Comment by dkd-kaehm** [comment]
This Pull-Request is still relevant.
@cjanody Would you like to continue or pass it on to someone else?

**Comment by cjanody** [comment]
@dkd-kaehm I can pass it. I haven't had time to work on for a while... Thks

**Pull request closed without merging**
