### PR TITLE
[BUGFIX]  [PHP7] Incompatible override of Apache_Solr_Service::extract in ApacheSolrForTypo3\Solr\SolrService 

### PR DESCRIPTION
**Pull request by timoschmidt**
Renamed method extract to extractByQuery because the signature of the

overwritten method is not compatible. Added integration test for pdf extraction as well.

Fixes: #198

Needs change in EXT:tika

### CODE REVIEW

**Comment by timoschmidt** [comment]
After merging we need to use ApacheSolrForTypo3\Solr\SolrService::extractByQuery in EXT:tika

**Comment by irnnr** [comment]
Alternatively I was thinking we could move this into EXT:tika altogether. This way we would not have a breaking change in dependencies on the tika side. OTOH EXT:tika could have checks of course whether the method exists or what EXT:solr version is being used.

What do you think?

**Comment by timoschmidt** [comment]
I would propose to keep it in EXT:solr because the extract functionallity is maybe usefull as api for other extensions to. When we would move it to EXT:tika it would be an API Change nevertheless.

**Comment by irnnr** [comment]
ok, sounds good

**Pull request merged**
